### ISSUE TITLE
PoS list is in Czech for Urdu corpus

### ISSUE THREAD

**Issue by amirkamran** [ufal/lindat-kontext#27]
click [here](https://lindat.mff.cuni.cz/services/kontext/run.cgi/first?shuffle=1&reload=1&corpname=urducorp_ur_m&queryselector=wordrow&iquery=&lemma=&lpos=&phrase=&word=&wpos=&char=&cql=&default_attr=word&fc_lemword_window_type=both&fc_lemword_wsize=5&fc_lemword=&fc_lemword_type=all&fc_pos_window_type=both&fc_pos_wsize=5&fc_pos_type=all&sca_doc.id=&sca_doc.wordcount=&sca_s.id=&sel_aligned=czeng_10_en_a&pcq_pos_neg_czeng_10_en_a=pos&queryselector_czeng_10_en_a=iqueryrow&iquery_czeng_10_en_a=&lpos_czeng_10_en_a=&wpos_czeng_10_en_a=&viewmode=align) and see the values in the PoS drop down.

Also, if you change query type to CQL it shows a link to tagset summary. The link does not work.

**Comment by natalink** [comment]
Do you know which tagset is used in Urdu corpus so that I can change the link? It looks like Penn at first sight, but there are another labels for adjectives(ADJ) and prepositions. Example: 
```
’|PN میرے|G بھائی|NN کا|P ای|PN میل|U آیاہے|VB ۔|SM
بلال|PN بھائی|PN ،|PM ہم|PP آپ|PP کی|P محنت|NN کے|P معترف|NN اور|CC قائل|ADJ ہیں|VB ۔|SM
اکیس|CA ستمبر|PN دو|CA ہزار|CA آٹھ|CA کو|P میریئٹ|ADJ ہوٹل|NN پر|P ٹرک|NN خود|RP کش|ADJ حملے|NN میں|P چون|CA افراد|NN ہلاک|ADJ ہوئے|VB جبکہ|SC اڑھائی|PN سو|VB سے|SE زائد|ADJ زخمی|ADJ ہوئے|VB ۔|SM
```
I can change the tagset link to: https://www.ling.upenn.edu/courses/Fall_2003/ling001/penn_treebank_pos.html
Also, either me or Michal J. (not sure who compiled it) used the default feature WPOSLIST for Czech:
```
WPOSLIST ",podstatné jméno,N.*,přídavné jméno,A.*,zájmeno,P.*,číslovka,C.*,sloveso,V.*,příslovce,D.*,předložka,R.*,spojka,J.*,částice,T.*,citoslovce,I.*,interpunkce,Z.*,neznámý,X.*"
```
If you can sent me the same line with urdu tags, like ",noun,N.*,adjective,ADJ, " etc... because I'm not sure about the tags, I will change the registry.

ps. Personally, I think that the query type "WordForm" can be substituted with CQL query like [word="whatever" & pos="N.*"]

**Comment by vidiecan** [comment]
@Ansa211 can you fix this one?
