### ISSUE TITLE
Example corpora

### ISSUE THREAD

**Issue by kosarko** [ufal/lindat-kontext#46]
Easily add compiled corpora to local installation. E.g. a script pulling compiled corpora from public repository. (or another "easy" way).

**Edit:** the target audience here are the developers. You want to enhance the UI or add new features; you want some data to test it with. If you have some well known datasets you can write automated tests on them etc.

**Comment by Ansa211** [comment]
In my view, this should be part of the pipeline for compiling corpora rather than part of KonText code. In other words, it should be possible to trigger the addition (or an update of a previously added corpus) from wherever the compilation is run.

**Comment by Ansa211** [comment]
In my view, this should be part of the pipeline for compiling corpora rather than part of KonText code. In other words, it should be possible to trigger the addition (or an update of a previously added corpus) from wherever the compilation is run.

I see two possible issues with this, both related to https://github.com/ufal/lindat-corpora-conversions#compilation:
- the new corpus has to be added to the `<corplist>` section of `config.xml`; I think the information about individual corpora should actually be automatically taken from the registry file of the corpus, but currently some values, such as the "repo" and "pmltq" attributes, do not even appear inside the registry files; moreover, the `<corplist>` elements can be nested, providing a grouping of corpora, which cannot be achieved with the registry files alone 
- in case of a corpus with a treex view (the json files), actual kontext code has to be adjusted,
 see https://github.com/ufal/lindat-kontext/issues/9#issuecomment-308411909

**Comment by vidiecan** [comment]
@kosarko the description is too vague, see @Ansa211 comment (misunderstanding)

**Comment by kosarko** [comment]
@Ansa211 the target audience here are the developers. You want to enhance the UI or add new features; you want some data to test it with. If you have some well known datasets you can write automated tests on them etc.

So I'm hoping that any corpus that's currently listed in http://lindat.mff.cuni.cz/services/kontext/run.cgi/corplist can be "copied" into a fresh installation, that'll run locally on developers machine.
The task here is to make some sensible selection (representatives of audio, parallel, permissive license, not too huge in size) of already compiled corpora, make these compiled versions available "publicly" (something like https://github.com/ufal/lindat-kontext-ovm) and have a script that'll handle the "copying into" part (from the public location).

Please, do comment if you see any issues with this.

**Comment by vidiecan** [comment]
I think that this one can be fixed once #45 is closed

**Comment by kosarko** [comment]
checkout of https://github.com/ufal/lindat-test-corpora part of install script #45
