### ISSUE TITLE
On token mouse over not working as expected

### ISSUE THREAD

**Issue by vidiecan** [ufal/lindat-kontext#87]
How to reproduce:
Results->Display options->[Viewing options]->on token mouse over

Expected:
Something on mouse over

Happens:
Nothing

**Comment by Kira-D** [comment]
There is no such link "Display options" in kontext.korpus.cz.
But there is "Action", but it's not a link (see attachment).
![screen](https://user-images.githubusercontent.com/15314543/30277230-7458345e-9707-11e7-8492-631842059da3.png)

**Comment by Kira-D** [comment]
How to reproduce:
Results->Display options->[Viewing options]->on token mouse over
1. You should also choose some positional attributes (from Positional attributes).

Expected:
Something on mouse over
2. You will get an attribute or a set of a attributes on mouse over

Happens:
Nothing
3. It does not work by clicking on Display options in result area, but the same functionality is available from the menu: View -> Attributes, structures and references...
and it does work.
It seems, there is a problem with synchronizing the setting from two different places, the current version of kontext.korpus.cz uses this mouse over feature only from the menu.

**Comment by Kira-D** [comment]
@vidiecan  In our current version it is partially fixed. It works for logged in users and it doesn't work for anonymous users (And this is the correct behaviour except that it should not be available for clicking to anonymous user).
I can see to options:
1. Since the feature is doubled in two places, I can delete "Display options" from UI (completely). It is still available from View -> Attributes, structures and references
2. I'll try to disable it for anonymous users

**Comment by vidiecan** [comment]
@Kira-D can you ask tomas the reason for the duplicate? if there is no good reason, delete one of them

**Comment by Kira-D** [comment]
@vidiecan  The answer is:
During the 0.9 development we at the CNC were discussing whether to introduce a toolbar with some "quick access" functions.  We were unable to agree on anything reasonable but some of the functionality remained in KonText as optional. Please check configuration value global/use_conc_toolbar to disable this. In recent KonText version, the toolbar contains only a status icon showing whether token mouseover metainformation is enabled or not. Previous versions contained also a button for quick display options access

I checked the config, it works, so I thing no change is needed.

**Comment by Kira-D** [comment]
A further discussion in Slack revealed that the feature is being used and should stay turned on in the config file.

A copypasted part of the discussion:
kira [11:43 AM] 
@tomachalek Kontext-0.9 has a link "Display options" at the view form (search results). The same functionality is available from from View -> Attributes, structures and references. I can see that in the current kontext.korpus.cz the link is removed. So I wonder if there is any reason for this duplicate in 0.9?

tomachalek [11:53 AM] 
@kira During the 0.9 development we at the CNC were discussing whether to introduce a toolbar with some "quick access" functions.  We were unable to agree on anything reasonable but some of the functionality remained in KonText as optional. Please check configuration value global/use_conc_toolbar to disable this. In recent KonText version, the toolbar contains only a status icon showing whether token mouseover metainformation is enabled or not. Previous versions contained also a button for quick display options access.

pavel [3:18 PM] 
Personally I do like the quick view options without going to the menu all the time. Depending on what I do I tend to change these options often (and depending on what analysis is available in that particular corpus).

ansa [10:10 PM] 
@kira @tomachalek I agree with @pavel, I enjoy the quick access toolbar. I think it would be worth developing it further instead of removing it :slightly_smiling_face: E.g. for my personal use, it would be nice if it would contain "New query", and "Positive" and "Negative filter". I like icon-only menus - for these three functions, the icons could be a magnifying glass, a magnifying glass with a + sign in it, and a magnifying glass with a - sign in it; the choice between "icons only" and "icons and text" could be set somewhere in the preferences (with "icons and text" being the default). The icons-only version would probably still fit into the top line (starting with "Hits:" and ending with the pager). At UČNK, the "New query" function is quickly available through the logo, but that is not the case on lindat.
